// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/transactions.proto

package transactions_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FraudEngine_EvaluateTransaction_FullMethodName = "/transactions.FraudEngine/EvaluateTransaction"
)

// FraudEngineClient is the client API for FraudEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FraudEngineClient interface {
	EvaluateTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*EvaluationResponse, error)
}

type fraudEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewFraudEngineClient(cc grpc.ClientConnInterface) FraudEngineClient {
	return &fraudEngineClient{cc}
}

func (c *fraudEngineClient) EvaluateTransaction(ctx context.Context, in *TransactionRequest, opts ...grpc.CallOption) (*EvaluationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluationResponse)
	err := c.cc.Invoke(ctx, FraudEngine_EvaluateTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FraudEngineServer is the server API for FraudEngine service.
// All implementations must embed UnimplementedFraudEngineServer
// for forward compatibility.
type FraudEngineServer interface {
	EvaluateTransaction(context.Context, *TransactionRequest) (*EvaluationResponse, error)
	mustEmbedUnimplementedFraudEngineServer()
}

// UnimplementedFraudEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFraudEngineServer struct{}

func (UnimplementedFraudEngineServer) EvaluateTransaction(context.Context, *TransactionRequest) (*EvaluationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateTransaction not implemented")
}
func (UnimplementedFraudEngineServer) mustEmbedUnimplementedFraudEngineServer() {}
func (UnimplementedFraudEngineServer) testEmbeddedByValue()                     {}

// UnsafeFraudEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FraudEngineServer will
// result in compilation errors.
type UnsafeFraudEngineServer interface {
	mustEmbedUnimplementedFraudEngineServer()
}

func RegisterFraudEngineServer(s grpc.ServiceRegistrar, srv FraudEngineServer) {
	// If the following call panics, it indicates UnimplementedFraudEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FraudEngine_ServiceDesc, srv)
}

func _FraudEngine_EvaluateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FraudEngineServer).EvaluateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FraudEngine_EvaluateTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FraudEngineServer).EvaluateTransaction(ctx, req.(*TransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FraudEngine_ServiceDesc is the grpc.ServiceDesc for FraudEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FraudEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transactions.FraudEngine",
	HandlerType: (*FraudEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EvaluateTransaction",
			Handler:    _FraudEngine_EvaluateTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/transactions.proto",
}

const (
	Settlement_CommitTransaction_FullMethodName = "/transactions.Settlement/CommitTransaction"
)

// SettlementClient is the client API for Settlement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SettlementClient interface {
	CommitTransaction(ctx context.Context, in *SettlementRequest, opts ...grpc.CallOption) (*SettlementResponse, error)
}

type settlementClient struct {
	cc grpc.ClientConnInterface
}

func NewSettlementClient(cc grpc.ClientConnInterface) SettlementClient {
	return &settlementClient{cc}
}

func (c *settlementClient) CommitTransaction(ctx context.Context, in *SettlementRequest, opts ...grpc.CallOption) (*SettlementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SettlementResponse)
	err := c.cc.Invoke(ctx, Settlement_CommitTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettlementServer is the server API for Settlement service.
// All implementations must embed UnimplementedSettlementServer
// for forward compatibility.
type SettlementServer interface {
	CommitTransaction(context.Context, *SettlementRequest) (*SettlementResponse, error)
	mustEmbedUnimplementedSettlementServer()
}

// UnimplementedSettlementServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSettlementServer struct{}

func (UnimplementedSettlementServer) CommitTransaction(context.Context, *SettlementRequest) (*SettlementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitTransaction not implemented")
}
func (UnimplementedSettlementServer) mustEmbedUnimplementedSettlementServer() {}
func (UnimplementedSettlementServer) testEmbeddedByValue()                    {}

// UnsafeSettlementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SettlementServer will
// result in compilation errors.
type UnsafeSettlementServer interface {
	mustEmbedUnimplementedSettlementServer()
}

func RegisterSettlementServer(s grpc.ServiceRegistrar, srv SettlementServer) {
	// If the following call panics, it indicates UnimplementedSettlementServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Settlement_ServiceDesc, srv)
}

func _Settlement_CommitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettlementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettlementServer).CommitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Settlement_CommitTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettlementServer).CommitTransaction(ctx, req.(*SettlementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Settlement_ServiceDesc is the grpc.ServiceDesc for Settlement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Settlement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transactions.Settlement",
	HandlerType: (*SettlementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CommitTransaction",
			Handler:    _Settlement_CommitTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/transactions.proto",
}
