// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/transactions.proto

package transactions_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxStatus int32

const (
	TxStatus_STATUS_UNKNOWN         TxStatus = 0
	TxStatus_STATUS_COMMITTED       TxStatus = 1
	TxStatus_STATUS_REJECTED_FRAUD  TxStatus = 2
	TxStatus_STATUS_ABORTED_TIMEOUT TxStatus = 3
)

// Enum value maps for TxStatus.
var (
	TxStatus_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_COMMITTED",
		2: "STATUS_REJECTED_FRAUD",
		3: "STATUS_ABORTED_TIMEOUT",
	}
	TxStatus_value = map[string]int32{
		"STATUS_UNKNOWN":         0,
		"STATUS_COMMITTED":       1,
		"STATUS_REJECTED_FRAUD":  2,
		"STATUS_ABORTED_TIMEOUT": 3,
	}
)

func (x TxStatus) Enum() *TxStatus {
	p := new(TxStatus)
	*p = x
	return p
}

func (x TxStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_transactions_proto_enumTypes[0].Descriptor()
}

func (TxStatus) Type() protoreflect.EnumType {
	return &file_proto_transactions_proto_enumTypes[0]
}

func (x TxStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxStatus.Descriptor instead.
func (TxStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_transactions_proto_rawDescGZIP(), []int{0}
}

type TransactionRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TxId                string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	UserId              string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CardToken           string                 `protobuf:"bytes,3,opt,name=card_token,json=cardToken,proto3" json:"card_token,omitempty"`
	Amount              float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	MerchantCategory    string                 `protobuf:"bytes,5,opt,name=merchant_category,json=merchantCategory,proto3" json:"merchant_category,omitempty"`
	Latitude            float64                `protobuf:"fixed64,6,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude           float64                `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	EmissionTimestampNs int64                  `protobuf:"varint,8,opt,name=emission_timestamp_ns,json=emissionTimestampNs,proto3" json:"emission_timestamp_ns,omitempty"`
	DeadlineBudgetMs    int32                  `protobuf:"varint,9,opt,name=deadline_budget_ms,json=deadlineBudgetMs,proto3" json:"deadline_budget_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *TransactionRequest) Reset() {
	*x = TransactionRequest{}
	mi := &file_proto_transactions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionRequest) ProtoMessage() {}

func (x *TransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transactions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionRequest.ProtoReflect.Descriptor instead.
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_transactions_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *TransactionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TransactionRequest) GetCardToken() string {
	if x != nil {
		return x.CardToken
	}
	return ""
}

func (x *TransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *TransactionRequest) GetMerchantCategory() string {
	if x != nil {
		return x.MerchantCategory
	}
	return ""
}

func (x *TransactionRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *TransactionRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *TransactionRequest) GetEmissionTimestampNs() int64 {
	if x != nil {
		return x.EmissionTimestampNs
	}
	return 0
}

func (x *TransactionRequest) GetDeadlineBudgetMs() int32 {
	if x != nil {
		return x.DeadlineBudgetMs
	}
	return 0
}

type EvaluationResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TxId             string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	IsFraud          bool                   `protobuf:"varint,2,opt,name=is_fraud,json=isFraud,proto3" json:"is_fraud,omitempty"`
	RejectionReason  string                 `protobuf:"bytes,3,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	RiskScore        float64                `protobuf:"fixed64,4,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	IsDegraded       bool                   `protobuf:"varint,5,opt,name=is_degraded,json=isDegraded,proto3" json:"is_degraded,omitempty"`
	ProcessingTimeMs int64                  `protobuf:"varint,6,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EvaluationResponse) Reset() {
	*x = EvaluationResponse{}
	mi := &file_proto_transactions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationResponse) ProtoMessage() {}

func (x *EvaluationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transactions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationResponse.ProtoReflect.Descriptor instead.
func (*EvaluationResponse) Descriptor() ([]byte, []int) {
	return file_proto_transactions_proto_rawDescGZIP(), []int{1}
}

func (x *EvaluationResponse) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *EvaluationResponse) GetIsFraud() bool {
	if x != nil {
		return x.IsFraud
	}
	return false
}

func (x *EvaluationResponse) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *EvaluationResponse) GetRiskScore() float64 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *EvaluationResponse) GetIsDegraded() bool {
	if x != nil {
		return x.IsDegraded
	}
	return false
}

func (x *EvaluationResponse) GetProcessingTimeMs() int64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

type SettlementRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TxId                string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	UserId              string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount              float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Evaluation          *EvaluationResponse    `protobuf:"bytes,4,opt,name=evaluation,proto3" json:"evaluation,omitempty"`
	EmissionTimestampNs int64                  `protobuf:"varint,5,opt,name=emission_timestamp_ns,json=emissionTimestampNs,proto3" json:"emission_timestamp_ns,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SettlementRequest) Reset() {
	*x = SettlementRequest{}
	mi := &file_proto_transactions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementRequest) ProtoMessage() {}

func (x *SettlementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transactions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementRequest.ProtoReflect.Descriptor instead.
func (*SettlementRequest) Descriptor() ([]byte, []int) {
	return file_proto_transactions_proto_rawDescGZIP(), []int{2}
}

func (x *SettlementRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *SettlementRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SettlementRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SettlementRequest) GetEvaluation() *EvaluationResponse {
	if x != nil {
		return x.Evaluation
	}
	return nil
}

func (x *SettlementRequest) GetEmissionTimestampNs() int64 {
	if x != nil {
		return x.EmissionTimestampNs
	}
	return 0
}

type SettlementResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TxId              string                 `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Status            TxStatus               `protobuf:"varint,2,opt,name=status,proto3,enum=transactions.TxStatus" json:"status,omitempty"`
	EndToEndLatencyMs int64                  `protobuf:"varint,3,opt,name=end_to_end_latency_ms,json=endToEndLatencyMs,proto3" json:"end_to_end_latency_ms,omitempty"`
	Message           string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SettlementResponse) Reset() {
	*x = SettlementResponse{}
	mi := &file_proto_transactions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementResponse) ProtoMessage() {}

func (x *SettlementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transactions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementResponse.ProtoReflect.Descriptor instead.
func (*SettlementResponse) Descriptor() ([]byte, []int) {
	return file_proto_transactions_proto_rawDescGZIP(), []int{3}
}

func (x *SettlementResponse) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

func (x *SettlementResponse) GetStatus() TxStatus {
	if x != nil {
		return x.Status
	}
	return TxStatus_STATUS_UNKNOWN
}

func (x *SettlementResponse) GetEndToEndLatencyMs() int64 {
	if x != nil {
		return x.EndToEndLatencyMs
	}
	return 0
}

func (x *SettlementResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_transactions_proto protoreflect.FileDescriptor

const file_proto_transactions_proto_rawDesc = "" +
	"\n" +
	"\x18proto/transactions.proto\x12\ftransactions\"\xc2\x02\n" +
	"\x12TransactionRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"card_token\x18\x03 \x01(\tR\tcardToken\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12+\n" +
	"\x11merchant_category\x18\x05 \x01(\tR\x10merchantCategory\x12\x1a\n" +
	"\blatitude\x18\x06 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\a \x01(\x01R\tlongitude\x122\n" +
	"\x15emission_timestamp_ns\x18\b \x01(\x03R\x13emissionTimestampNs\x12,\n" +
	"\x12deadline_budget_ms\x18\t \x01(\x05R\x10deadlineBudgetMs\"\xdd\x01\n" +
	"\x12EvaluationResponse\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12\x19\n" +
	"\bis_fraud\x18\x02 \x01(\bR\aisFraud\x12)\n" +
	"\x10rejection_reason\x18\x03 \x01(\tR\x0frejectionReason\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x04 \x01(\x01R\triskScore\x12\x1f\n" +
	"\vis_degraded\x18\x05 \x01(\bR\n" +
	"isDegraded\x12,\n" +
	"\x12processing_time_ms\x18\x06 \x01(\x03R\x10processingTimeMs\"\xcf\x01\n" +
	"\x11SettlementRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12@\n" +
	"\n" +
	"evaluation\x18\x04 \x01(\v2 .transactions.EvaluationResponseR\n" +
	"evaluation\x122\n" +
	"\x15emission_timestamp_ns\x18\x05 \x01(\x03R\x13emissionTimestampNs\"\xa5\x01\n" +
	"\x12SettlementResponse\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\x12.\n" +
	"\x06status\x18\x02 \x01(\x0e2\x16.transactions.TxStatusR\x06status\x120\n" +
	"\x15end_to_end_latency_ms\x18\x03 \x01(\x03R\x11endToEndLatencyMs\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage*k\n" +
	"\bTxStatus\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10STATUS_COMMITTED\x10\x01\x12\x19\n" +
	"\x15STATUS_REJECTED_FRAUD\x10\x02\x12\x1a\n" +
	"\x16STATUS_ABORTED_TIMEOUT\x10\x032h\n" +
	"\vFraudEngine\x12Y\n" +
	"\x13EvaluateTransaction\x12 .transactions.TransactionRequest\x1a .transactions.EvaluationResponse2d\n" +
	"\n" +
	"Settlement\x12V\n" +
	"\x11CommitTransaction\x12\x1f.transactions.SettlementRequest\x1a .transactions.SettlementResponseB\x1eZ\x1cfd_rts/proto/transactions_pbb\x06proto3"

var (
	file_proto_transactions_proto_rawDescOnce sync.Once
	file_proto_transactions_proto_rawDescData []byte
)

func file_proto_transactions_proto_rawDescGZIP() []byte {
	file_proto_transactions_proto_rawDescOnce.Do(func() {
		file_proto_transactions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_transactions_proto_rawDesc), len(file_proto_transactions_proto_rawDesc)))
	})
	return file_proto_transactions_proto_rawDescData
}

var file_proto_transactions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_transactions_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_transactions_proto_goTypes = []any{
	(TxStatus)(0),              // 0: transactions.TxStatus
	(*TransactionRequest)(nil), // 1: transactions.TransactionRequest
	(*EvaluationResponse)(nil), // 2: transactions.EvaluationResponse
	(*SettlementRequest)(nil),  // 3: transactions.SettlementRequest
	(*SettlementResponse)(nil), // 4: transactions.SettlementResponse
}
var file_proto_transactions_proto_depIdxs = []int32{
	2, // 0: transactions.SettlementRequest.evaluation:type_name -> transactions.EvaluationResponse
	0, // 1: transactions.SettlementResponse.status:type_name -> transactions.TxStatus
	1, // 2: transactions.FraudEngine.EvaluateTransaction:input_type -> transactions.TransactionRequest
	3, // 3: transactions.Settlement.CommitTransaction:input_type -> transactions.SettlementRequest
	2, // 4: transactions.FraudEngine.EvaluateTransaction:output_type -> transactions.EvaluationResponse
	4, // 5: transactions.Settlement.CommitTransaction:output_type -> transactions.SettlementResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_transactions_proto_init() }
func file_proto_transactions_proto_init() {
	if File_proto_transactions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_transactions_proto_rawDesc), len(file_proto_transactions_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_transactions_proto_goTypes,
		DependencyIndexes: file_proto_transactions_proto_depIdxs,
		EnumInfos:         file_proto_transactions_proto_enumTypes,
		MessageInfos:      file_proto_transactions_proto_msgTypes,
	}.Build()
	File_proto_transactions_proto = out.File
	file_proto_transactions_proto_goTypes = nil
	file_proto_transactions_proto_depIdxs = nil
}
